### ISSUE TITLE
The system cannot find the path specified error on VS Code extension

### ISSUE THREAD

**Issue by ciricc** [numary/numscript-ls#3]
I have got an error when tried to use vs code extension.
Built server on Windows 11 x64

```Starting Numscript Language Server...
panic: could not open file: open /d%3A/projects/numscript_test/dd.num: The system cannot find the path specified.

goroutine 1 [running]:
main.glob..func3(0xc04a20, 0xc000004a50)
	D:/projects/numscript-ls/handlers.go:122 +0x11b
main.(*Server).Run(0xc4b33b)
	D:/projects/numscript-ls/main.go:122 +0x113
main.main()
	D:/projects/numscript-ls/main.go:136 +0x90
[Error - 02:12:18] Connection to server got closed. Server will not be restarted.```

**Comment by ciricc** [comment]
Code like this fixes this error

```go
path := string(uri[7:])
if runtime.GOOS == "windows" {
  windowsFilePath, err := url.PathUnescape(path)
  if err != nil {
	  panic("could not unescape file uri: " + err.Error())
  }
  windowsFilePath = strings.TrimPrefix(windowsFilePath, "/")
  path = windowsFilePath
}
```

**Comment by altitude** [comment]
Fantastic thanks @ciricc! Do you wanna go ahead and make a PR?
